Fixes copy.
Otherwise fails:

	/var/log # logrotate -fv /etc/logrotate.d/java
	reading config file /etc/logrotate.d/java
	Reading state from file: /var/lib/logrotate.status
	Allocating hash table for state file, size 64 entries
	Creating new state
	Creating new state

	Handling 1 logs

	rotating pattern: /var/log/err
	/var/log/out
	 forced from command line (no old logs will be kept)
	empty log files are rotated, old logs are removed
	considering log /var/log/err
	  Now: 2022-09-14 03:43
	  Last rotated at 2022-09-14 03:42
	  log needs rotating
	considering log /var/log/out
	  Now: 2022-09-14 03:43
	  Last rotated at 2022-09-14 03:42
	  log needs rotating
	rotating log /var/log/err, log->rotateCount is 0
	dateext suffix '-20220914'
	glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
	renaming /var/log/err.1.gz to /var/log/err.2.gz (rotatecount 1, logstart
	1, i 1),
	old log /var/log/err.1.gz does not exist
	renaming /var/log/err.0.gz to /var/log/err.1.gz (rotatecount 1, logstart
	1, i 0),
	old log /var/log/err.0.gz does not exist
	log /var/log/err.2.gz doesn't exist -- won't try to dispose of it
	copying /var/log/err to /var/log/err.1
	truncating /var/log/err
	compressing log with: /bin/gzip
	error: unable to open /var/log/err.1 (read-only) for compression: No
	such file or directory
	rotating log /var/log/out, log->rotateCount is 0
	dateext suffix '-20220914'
	glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
	renaming /var/log/out.1.gz to /var/log/out.2.gz (rotatecount 1, logstart
	1, i 1),
	old log /var/log/out.1.gz does not exist
	renaming /var/log/out.0.gz to /var/log/out.1.gz (rotatecount 1, logstart
	1, i 0),
	old log /var/log/out.0.gz does not exist
	log /var/log/out.2.gz doesn't exist -- won't try to dispose of it
	copying /var/log/out to /var/log/out.1
	truncating /var/log/out
	compressing log with: /bin/gzip
	error: unable to open /var/log/out.1 (read-only) for compression: No
	such file or directory
	running last action script
	ls: *.gz: No such file or directory

Check:
	https://community.spiceworks.com/topic/2352199-logrotate-copy-options-do-not-work